use_frameworks!

platform :ios, '10.0'

target 'YDSafeThread_Example' do
  pod 'YDSafeThread', :path => '../'

  target 'YDSafeThread_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
